Kubernetes intro
otus-kuber-2021-03/ebabaev_platform pull request #3
Opened 2021-04-08 15:23 UTC by ebabaev

2021-04-08 15:29 UTC, ebabaev commented
Добрый день. В чем ошибка теста?

2021-04-08 15:49 UTC, Jasstkn requested changes

2021-04-08 15:49 UTC, Jasstkn commented on kubernetes-intro/web/Dockerfile
> +  chown -R ${NGINX_PORT} /var/cache/nginx
Похоже опечатались и тут должен быть USER

2021-04-09 05:25 UTC, ebabaev commented on kubernetes-intro/web/Dockerfile
> +  chown -R ${NGINX_PORT} /var/cache/nginx
Странно, я даже не заметил и контейнер работал нормально и под. Я поправил, как перезапутить тесты?

2021-04-09 17:33 UTC, Jasstkn commented on kubernetes-intro/web/Dockerfile
> +  chown -R ${NGINX_PORT} /var/cache/nginx
Они сами перезапускаются, но в вашем случае возможно причина еще в чем-то. Сейчас попробую локально под запустить

2021-04-09 17:35 UTC, Jasstkn commented on kubernetes-intro/web-pod.yaml
> +  name: web-app
имя пода просто web должно быть

2021-04-09 17:35 UTC, Jasstkn commented on kubernetes-intro/web/Dockerfile
> +  chown -R ${NGINX_PORT} /var/cache/nginx
Нашла ошибку - отписалась

2021-04-21 09:39 UTC, merged